using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Celeste.Mod.Roslyn.ModLifecycleAttributes;

// a StringBuilder-based source generator with a bunch of convenience features
// adopted from my ModInteropImportGenerator implementation
// https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.cookbook.md#use-an-indented-text-writer-not-syntaxnodes-for-generation
public class SimpleSourceGenerator
{
    private readonly SortedSet<string> Usings = new(StringComparer.Ordinal);
    private readonly StringBuilder SourceCode = new();
    private bool ShouldIndentLine = true;
    public string? Namespace;

    private int _IndentLevel;
    public int IndentLevel
    {
        get => _IndentLevel;
        set => _IndentLevel = value < 0 ? 0 : value;
    }

    public SimpleSourceGenerator()
    {
    }

    public SimpleSourceGenerator(string? @namespace) => Namespace = @namespace;

    public SimpleSourceGenerator AddUsing(string usingNamespace)
    {
        Usings.Add(usingNamespace);
        return this;
    }

    public SimpleSourceGenerator AddUsings(params IEnumerable<string> usingNamespaces)
    {
        foreach (string @namespace in usingNamespaces)
            Usings.Add(@namespace);
        return this;
    }

    public bool TryAddUsingFor(INamespaceSymbol @namespace)
        => Usings.Add(@namespace.ToDisplayString());

    public bool TryAddUsingFor(ITypeSymbol type)
        => type.ContainingNamespace is { } @namespace && TryAddUsingFor(@namespace);

    public SimpleSourceGenerator WriteLine()
    {
        if (ShouldIndentLine)
            WriteIndent();
        SourceCode.AppendLine();
        ShouldIndentLine = true;
        return this;
    }

    public SimpleSourceGenerator WriteLine(string line)
    {
        if (ShouldIndentLine)
            WriteIndent();
        SourceCode.AppendLine(line);
        ShouldIndentLine = true;
        return this;
    }

    public SimpleSourceGenerator WriteLine(char c)
    {
        if (ShouldIndentLine)
            WriteIndent();
        SourceCode.Append(c).AppendLine();
        ShouldIndentLine = true;
        return this;
    }

    public SimpleSourceGenerator Write(string line)
    {
        if (ShouldIndentLine)
            WriteIndent();
        SourceCode.Append(line);
        return this;
    }

    public SimpleSourceGenerator Write(char c)
    {
        if (ShouldIndentLine)
            WriteIndent();
        SourceCode.Append(c);
        return this;
    }

    public SimpleSourceGenerator Indent(int indentCount = 1)
    {
        IndentLevel += indentCount;
        return this;
    }

    public SimpleSourceGenerator Dedent(int dedentCount = 1)
    {
        IndentLevel -= dedentCount;
        return this;
    }

    public IndentContext UseIndent(int indentCount = 1)
        => new(this, indentCount);

    public IndentedCodeBlockContext UseCodeBlock(int indentCount = 1, bool withSemicolon = false)
        => new(this, indentCount, withSemicolon);

    private void WriteIndent()
    {
        ShouldIndentLine = false;
        if (IndentLevel <= 0)
            return;

        for (int i = 0; i < IndentLevel; i++)
        for (int j = 0; j < 4; j++)
            SourceCode.Append(' ');
    }

    public string Generate()
    {
        StringBuilder generator = new();
        generator.AppendLine("// <auto-generated />");
        generator.AppendLine();

        if (Usings.Count > 0)
        {
            foreach (string t in Usings)
                generator.AppendLine($"using {t};");
            generator.AppendLine();
        }

        if (Namespace is not null)
        {
            generator.AppendLine($"namespace {Namespace};");
            generator.AppendLine();
        }

        for (int i = 0; i < SourceCode.Length; i++)
            generator.Append(SourceCode[i]);

        return generator.ToString();
    }

    public ref struct IndentContext : IDisposable
    {
        private readonly SimpleSourceGenerator SourceGen;
        private readonly int IndentCount;

        private bool Disposed;

        public IndentContext(SimpleSourceGenerator sourceGen, int indentCount)
        {
            SourceGen = sourceGen;
            IndentCount = indentCount;

            sourceGen.IndentLevel += indentCount;
        }

        public void Dispose()
        {
            if (Disposed)
                throw new ObjectDisposedException(nameof(IndentContext));

            Disposed = true;
            SourceGen.IndentLevel -= IndentCount;
        }
    }

    public ref struct IndentedCodeBlockContext : IDisposable
    {
        private readonly SimpleSourceGenerator SourceGen;
        private readonly int IndentCount;
        private readonly bool WithSemicolon;

        private bool Disposed;

        public IndentedCodeBlockContext(SimpleSourceGenerator sourceGen, int indentCount, bool withSemicolon)
        {
            SourceGen = sourceGen;
            IndentCount = indentCount;
            WithSemicolon = withSemicolon;

            sourceGen.WriteLine('{');
            sourceGen.IndentLevel += indentCount;
        }

        public void Dispose()
        {
            if (Disposed)
                throw new ObjectDisposedException(nameof(IndentedCodeBlockContext));

            Disposed = true;
            SourceGen.IndentLevel -= IndentCount;
            SourceGen.Write('}');
            if (WithSemicolon)
                SourceGen.Write(';');
            SourceGen.WriteLine();
        }
    }
}
